// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVHGJqzRGohQaT6SFe8PCbP32lGE5FKC8',
    appId: '1:593903823276:web:deab98522447c96925f209',
    messagingSenderId: '593903823276',
    projectId: 'catering-23ce0',
    authDomain: 'catering-23ce0.firebaseapp.com',
    storageBucket: 'catering-23ce0.firebasestorage.app',
    measurementId: 'G-BK5KG3HJ6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEwxnWOlkOTfZpqOgBm3HfCfr-4O--5qM',
    appId: '1:593903823276:android:afba3901fe639ba925f209',
    messagingSenderId: '593903823276',
    projectId: 'catering-23ce0',
    storageBucket: 'catering-23ce0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfX0VIPRgwba-sOq-TQECmFTxTEN2LA0k',
    appId: '1:593903823276:ios:b873512d83b31c5325f209',
    messagingSenderId: '593903823276',
    projectId: 'catering-23ce0',
    storageBucket: 'catering-23ce0.firebasestorage.app',
    iosBundleId: 'com.example.cateringMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfX0VIPRgwba-sOq-TQECmFTxTEN2LA0k',
    appId: '1:593903823276:ios:b873512d83b31c5325f209',
    messagingSenderId: '593903823276',
    projectId: 'catering-23ce0',
    storageBucket: 'catering-23ce0.firebasestorage.app',
    iosBundleId: 'com.example.cateringMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVHGJqzRGohQaT6SFe8PCbP32lGE5FKC8',
    appId: '1:593903823276:web:059feeec75da277725f209',
    messagingSenderId: '593903823276',
    projectId: 'catering-23ce0',
    authDomain: 'catering-23ce0.firebaseapp.com',
    storageBucket: 'catering-23ce0.firebasestorage.app',
    measurementId: 'G-HJQ4PS5MMG',
  );
}
